# Generated by Django 4.2.1 on 2023-05-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.JSONField()),
                ('database_refresh_date', models.DateTimeField()),
            ],
        ),
    ]
